# config/packages/twig.yaml
twig:
    default_path: '%kernel.project_dir%/templates'
    
    # Bu satır tam olarak 'twig:'in bir kademe altında olmalı
    form_themes:
        - 'form/tailwind_layout.html.twig'
    globals:
        profiles: '%profiles%'
        
when@test:
    twig:
        strict_variables: true
